napalm-automation/napalm

napalm/base.py
added description and more prefix count
=> bgp data structure additions

Manifest.in, napalm/junos.py, utils/junos_views.py, utils/junos_views.yml
and basic bgp and lldp neigh tables/views (<- untested)
=> added junos facts() and interfaces()

ansible/napalm_install_config
Change-Id: I3ef18b92c7c1795d19920f04e525f712740b5fc0
=> unicode problem

ansible/napalm_install_config, napalm/junos.py
Update of #64 against the 0.30 branch.
=> Make Junos timeout configurable

docs/conf.py
This is a super tiny change to fix autodoc so I am merging myself. I hope nobody objects ; )
=> Fixing autodoc

napalm/eos.py
Change-Id: I59479f43f3aae89c997408efc7a9538344aeed57
=> Adding environment for EOS

docs/support/index.rst, docs/support/ios.rst, napalm/__init__.py, napalm/ios.py, requirements.txt, test/unit/TestIOSDriver.py, test/unit/ios/initial.conf, test/unit/ios/merge_good.conf, test/unit/ios/merge_typo.conf
Hi there.
This started as an 'exercise' for myself but I decided to make the PR since I'd like to contribute to this awesome project.
Working with IOS is a pain since it doesn't have native API, but I tried to do my best to meet the project requirements. It's far to be completed yet, but if you think this could be useful I'll keep working on it (like adding compare function and fine tuning the whole thing).
Let me know :)
=> Started adding IOS support

napalm/eos.py
Change-Id: I15d7dd4f7e282ea6f6cadbec2d1a694aec4c6fd0
=> Adding get_bgp_neighbors to eos.py

napalm/eos.py, test/unit/base.py, test/unit/eos/mock_data/show_ip_bgp_neighbors_vrf_all_|_include_remote_AS|remote_router_ID|Description|^_*IPv[4-6]_Unicast:.txt, test/unit/eos/mock_data/show_ip_bgp_summary_vrf_all.json, test/unit/eos/mock_data/show_ipv6_bgp_neighbors_vrf_all_|_include_remote_AS|remote_router_ID|Description|^_*IPv[4-6]_Unicast:.txt, test/unit/eos/mock_data/show_ipv6_bgp_summary_vrf_all.json
Change-Id: I0c5bd1528fa1dc80d88267e1e449766c1ecbb2ea
=> Mock data for EOS BGP neighbors

docs/support/index.rst, napalm/base.py, napalm/eos.py, napalm/fortios.py, napalm/ibm.py, napalm/ios.py, napalm/iosxr.py, napalm/junos.py, napalm/nxos.py
The idea behind this is that we can pass a dictionary with optional arguments that each specific driver can use.
=> Added support for optional_args

napalm/eos.py
Added support to pass the timeout arguement to pyeapi from EOSDriver
=> Added support to pass the timeout arguement to pyeapi from EOSDriver

docs/support/index.rst, napalm/base.py, napalm/eos.py, napalm/exceptions.py, napalm/iosxr.py, napalm/junos.py, napalm/nxos.py
=> Method CLI defined for JunOS, NXOS, IOS-XR & EOS

napalm/ios.py
this is to resolve this issue.
Fixes #187
=> modify device model regex for IOS

napalm/ios.py
Minor cleanup of ios driver for pylama.
=> pylama cleanup of Cisco IOS

docs/support/index.rst
Merge candidate, but only after https://github.com/napalm-automation/napalm-base/pull/16 and https://github.com/napalm-automation/napalm-base/pull/17.
=> Doc updates

.github/ISSUE_TEMPLATE
It's based on the ansible one because I thought it made sense to use it as a base to start discussing it.
=> ISSUE TEMPLATE

docs/support/index.rst
Add ping method to the docs following napalm-automation/napalm-ios#20
=> Add ping method to docs

docs/support/index.rst
relates napalm-automation/napalm-base#58
relates napalm-automation/napalm-eos#32
=> Updated index.rst

docs/tutorials/installation.rst
In response to issue #284 & PR #283 
This is just a quick initial draft of an installation page for the docs, for initial feedback, just to see if it's what you have in mind or if I'm wide of the mark.  Plus I don't know what other drivers have dependencies, and have only tested the Ubuntu installation dependencies.  The Installation & Upgrading instructions are just pulled verbatim from the napalm github README.
=> initial draft of installation.rst

docs/development/index.rst, docs/development/testing_framework.rst, docs/index.rst
Documentation for napalm-automation/napalm-base#42
=> Added documentation for the testing framework

docs/support/index.rst
https://github.com/napalm-automation/napalm-eos/pull/43
=> update docs for enable_password on eos

docs/support/index.rst
Adding entry in getters support matrix for new get_config method https://github.com/napalm-automation/napalm-base/issues/65
=> adding get_config to getters support matrix

docs/tutorials/lab.rst
To adapt to the last EOS version, suggest update the VEOS_BOX variable within the VagrantFile
=> Suggest VEOS_BOX change in Vagrantfile

docs/support/index.rst
Follow up from https://github.com/napalm-automation/napalm-panos/pull/23
=> Adding panos support for optional args

docs/support/index.rst
Noticed a few methods were supported but not documented in NXOS.
=> Update NXOS getters documentation

docs/validate/index.rst
Updated documentation for:
napalm-automation/napalm-base#175
napalm-automation/napalm-base#176
=> Updating documentation with validate support for kwargs and regexp

.gitignore, docs/validate/index.rst
* Add explanation of how the _name keyword works
=> Add explanation of how the _name keyword works (#346)

.gitignore, README.md, docs/support/index.rst, docs/validate/index.rst, requirements.txt, setup.py, test/unit/TestGetNetworkDriver.py
=> Release 1.2.0

docs/YANG/translators/TextTranslator.rst
Relates to https://github.com/napalm-automation/napalm-yang/pull/46
=> Documented end argument for the init_element of the text translator

docs/support/index.rst
This is for napalm-automation/napalm-junos#145
=> Update optional_args key_file documentation

docs/validate/index.rst
This PR is related napalm-base PR[#243](https://github.com/napalm-automation/napalm-base/pull/243).
For clarity I wrote the validation example of compare in ``get_environment`` and ``get_bgp_neighbors``.
=> Update documentation for napalm-base PR#243

docs/support/ios.rst
Some other minor documentation cleanup.
=> Adding banner requirements to IOS documentation

docs/support/index.rst
Update section optional_args to add ignore_warning for junos.
=> Update section optional_args: ignore_warning

README.md, docs/support/index.rst
Update ping documentation in Other Methods to be correct
=> Correct ping documentation in Other Methods

README.md, docs/support/index.rst, docs/validate/index.rst
The YAML is not properly nested in some of the examples in the documentation.
=> Fix incorrectly nested YAML in validate documentation.

docs/support/nxos.rst
=> Doc change NX-OS: fix reference to _get_checkpoint_file() and add example

.github/ISSUE_TEMPLATE, docs/cli.rst
For napalm-automation/napalm-base/pull/292
=> Updated documentation for the new cli

docs/support/index.rst, docs/tutorials/extend_driver.rst, docs/tutorials/index.rst
need some formatting help, but a start.
=> Napalm docs

docs/support/eos.rst, napalm/eos/eos.py, test/eos/test_heredoc.py
=> (eos) loop through loaded config to convert HEREDOC commands.  Fixes #519

napalm/nxos_ssh/nxos_ssh.py
So far this is working, I still need to verify that all values are returned correctly across all platforms. But take a look, run some tests, and I can work more on it next week.
=> NXOS XML Parser Support POC

napalm/base/clitools/cl_napalm_configure.py, napalm/base/clitools/cl_napalm_test.py, napalm/base/clitools/cl_napalm_validate.py, napalm/base/mock.py, napalm/base/test/getters.py, napalm/base/validate.py, napalm/eos/eos.py, napalm/ios/ios.py, napalm/iosxr/iosxr.py, napalm/junos/junos.py, napalm/nxos/nxos.py, napalm/nxos_ssh/nxos_ssh.py
Update test framework, CLI warnings, and regex raw strings to resolve warnings in Tox runs.
=> Resolve deprecation warnings in tests.

docs/contributing/core.rst, docs/contributing/drivers.rst, docs/contributing/index.rst
<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>
=> Documentation regarding core/community drivers

napalm/eos/eos.py, test/eos/test_heredoc.py
=> Convert doublebang comments in config to eAPI HEREDOC "comment" commands

docs/support/ios.rst, napalm/ios/ios.py
=> Don't enable scp automatically

napalm/iosxr/iosxr.py
https://github.com/napalm-automation/napalm-iosxr/releases/tag/0.5.6
Closes #532
=> Port napalm-iosxr 0.5.6 commits

napalm/nxos/__init__.py, napalm/nxos/nxos.py, napalm/nxos_ssh/nxos_ssh.py
Also add structure to share code between NX-API and NX-OS SSH code.
=> Fix NX-OS not saving config to startup-config

napalm/junos/junos.py
Resolve #646 .  Adding PTX to the list of Exception platforms
=> [646] updating junos.py to support PTX platform

docs/support/index.rst
=> Minor doc changes for NX-OS and IOS

setup.py
=> Fix setup.py issue when using pip 10.

docs/tutorials/lab.rst, docs/tutorials/wrapup.rst
Added the provider flag -as discussed in  #668 - and fix a couple of minor formatting issues in the documentation.
Kudos to the maintainers, this project makes my life much easier :)
=> Add virtualbox provider to the docs

napalm/base/__init__.py, napalm/base/helpers.py, napalm/eos/eos.py, napalm/junos/junos.py, napalm/nxos/nxos.py
=> Fixing deprecated use of e.message

docs/tutorials/index.rst, docs/tutorials/mock_driver.rst
@anthony25 Let's work on this tutorial here so anybody can see and contribute to this tutorial.
=> WIP: Add a tutorial to use Napalm mock driver

napalm/base/helpers.py
Hello,
A little patch to prevent file descriptor leaks :)
=> Fix ResourceWarning: unclosed file in base/helpers.py

napalm/eos/eos.py
Fixed the issue#766. Just added the missing $ (for end of line) to get the description.
=> fixing Issue #766

docs/tutorials/first_steps_config.rst
To support python3 as suggested in the Napalm channel in networkocode slack.
=> Updated print statements as function

napalm/junos/junos.py, test/junos/mocked_data/test_get_lldp_neighbors_detail/ex9208_qfx10008/facts.yml, test/junos/mocked_data/test_get_lldp_neighbors_detail/normal_ex_fx_srx/facts.yml, test/junos/mocked_data/test_get_lldp_neighbors_detail/normal_mx_m_t/facts.yml, test/junos/mocked_data/test_get_lldp_neighbors_detail/qfx5110/facts.yml, test/junos/mocked_data/test_get_lldp_neighbors_detail/srx4100/facts.yml
=> Refactor LLDP neighbors detail on Junos

.travis.yml, napalm/base/test/base.py, napalm/ios/ios.py, napalm/iosxr/iosxr.py, napalm/junos/junos.py, requirements-dev.txt
There are some other fixes in this PR that are related to pyflakes changes breaking the build and some minor cleanup.
=> Fix issue where 'no file prompt' in configuration gets reverted due to commit or rollback

napalm/ios/ios.py, test/ios/mocked_data/test_get_mac_address_table/6500_6800_vss_format/expected_result.json, test/ios/mocked_data/test_get_mac_address_table/6500_6800_vss_format/show_mac_address_table.txt
=> support catalyst vss for mac_address getter

napalm/ios/ios.py, napalm/nxos/nxos.py, napalm/nxos_ssh/nxos_ssh.py
Fix merge issues on nxos_ssh; fix rollback issues on nxos_ssh and ios (for hostname changes).
=> Hostname fixes for NXOS and IOS

napalm/eos/eos.py
To fix(?) issue #1041 - https://github.com/napalm-automation/napalm/issues/1041
On branch eos-lock-disable-flag
Changes to be committed:
modified:   napalm/eos/eos.py
=> Implemented  lock_disable for EOS based on Junos.

docs/index.rst
Correct capitalization error on "extras".  Working through docs to clean up typos.
=> Update index.rst to fix typo

napalm/base/base.py
=> Fix simple typo: themselvs -> themselves

napalm/nxos_ssh/nxos_ssh.py, test/nxos_ssh/mocked_data/test_get_interfaces_ip/ip_address_none/expected_result.json, test/nxos_ssh/mocked_data/test_get_interfaces_ip/ip_address_none/show_ip_interface_vrf_all.txt, test/nxos_ssh/mocked_data/test_get_interfaces_ip/ip_address_none/show_ipv6_interface_vrf_all.txt
=> Handle 'none' IP Address on nxos_ssh for get_interfaces_ip

napalm/nxos_ssh/nxos_ssh.py, test/nxos_ssh/mocked_data/test_get_facts/does_not_support_json/expected_result.json, test/nxos_ssh/mocked_data/test_get_facts/does_not_support_json/show_hostname.txt, test/nxos_ssh/mocked_data/test_get_facts/does_not_support_json/show_hosts.txt, test/nxos_ssh/mocked_data/test_get_facts/does_not_support_json/show_interface_status.txt, test/nxos_ssh/mocked_data/test_get_facts/does_not_support_json/show_inventory.txt, test/nxos_ssh/mocked_data/test_get_facts/does_not_support_json/show_inventory___json.txt, test/nxos_ssh/mocked_data/test_get_facts/does_not_support_json/show_version.txt
https://github.com/napalm-automation/napalm/issues/1082
=> firmware less than 7 does not support json in cli

requirements.txt
=> Add requests as dependency

napalm/eos/eos.py, test/eos/mocked_data/test_get_lldp_neighbors_detail/issue1153/expected_result.json, test/eos/mocked_data/test_get_lldp_neighbors_detail/issue1153/show_lldp_neighbors__detail.json, test/eos/mocked_data/test_get_lldp_neighbors_detail/normal/expected_result.json
=> Fix #1153: Strip double quotation on LLDP remote port

napalm/eos/eos.py, test/eos/mocked_data/test_get_bgp_neighbors/issue1168/expected_result.json, test/eos/mocked_data/test_get_bgp_neighbors/issue1168/show_ip_bgp_neighbors_vrf_all___include_remote_AS___remote_router_ID__IPv_46___Unicast_6PE_____0_9____Local_AS_Desc_BGP_state.text, test/eos/mocked_data/test_get_bgp_neighbors/issue1168/show_ip_bgp_summary_vrf_all.json, test/eos/mocked_data/test_get_bgp_neighbors/issue1168/show_ipv6_bgp_neighbors_vrf_all___include_remote_AS___remote_router_ID__IPv_46___Unicast_6PE_____0_9____Local_AS_Desc_BGP_state.text, test/eos/mocked_data/test_get_bgp_neighbors/issue1168/show_ipv6_bgp_summary_vrf_all.json
=> Cast upDownTime BGP neighbor field to float

napalm/junos/junos.py
Fix for following issue:
https://github.com/napalm-automation/napalm/issues/1316
=> Add wildcard for set matches on junos

napalm/base/helpers.py, napalm/junos/junos.py
Fixes #1322 in napalm, other warnings are from outside libraries
=> correct collections import for python 3.3+

napalm/pyIOSXR/iosxr.py
=> Issue #1312: Remove the reference to Netmiko's receive_data_generator

docs/conf.py, docs/support/index.rst, docs/tutorials/changing_the_config.rst, docs/tutorials/index.rst
=> Commit confirm docs

docs/support/index.rst
Fixed typo in docs around delete_ntp_peers
=> Update index.rst to fix small typo

napalm/base/utils/string_parsers.py, napalm/eos/eos.py, napalm/nxos/nxos.py, requirements-dev.txt, test/pyiosxr/test_iosxr.py
Supersedes https://github.com/napalm-automation/napalm/pull/1430 and
makes the necessary changes to make Black checks happy.
=> Bump to Black 21.4b2

setup.py
=> Prepare version 4.0.0

napalm/iosxr_netconf/iosxr_netconf.py
=> Fix setting custom port for iosxr_netconf platform

napalm/base/base.py, napalm/base/models.py, napalm/eos/eos.py, napalm/ios/ios.py, napalm/iosxr/iosxr.py, napalm/iosxr_netconf/iosxr_netconf.py, napalm/junos/junos.py, napalm/nxos/nxos.py, napalm/nxos_ssh/nxos_ssh.py
=> [Fix] models

requirements-dev.txt
Incompatibility between pylama and pyflakes > 2.4.0
https://github.com/klen/pylama/issues/224
=> fix: pin pyflakes version

napalm/eos/eos.py
=> fix(eos): handle netmiko close

.github/workflows/commit.yaml, docs/requirements.txt, napalm/base/base.py, requirements-dev.txt
- Update mypy and fix one type hint issue
- Update GH actions checkout and setup-python
- Update markupsafe
- Update Sphinx
- Update Ansible
- Update Jinja2
=> Update docs depedencies, mypy, and gh-actions (checkout and setup-python)
