docs/ibm.rst, napalm/ibm.py, test/unit/TestIBMDriver.py, test/unit/base.py, test/unit/ibm/initial.conf, test/unit/ibm/merge_good.conf, test/unit/ibm/merge_good.diff, test/unit/ibm/merge_typo.conf, test/unit/ibm/new_good.conf, test/unit/ibm/new_good.diff, test/unit/ibm/new_typo.conf
This is the first version of module for IBM/Lenovo RackSwitch series. It uses netconf via library provided by Lenovo (mentioned in official manual). Module supports only configuration management features for now. There are couple of issues with netconf implementation on these devices and it will be described in documentation. Unit tests have been performed. Obviously there are 3 errors (getters are not implemented yet) and 1 error for "test_merge_configuration_typo_and_rollback". I can detect syntax error only during commit operations. I do not have problem with "test_replacing_config_with_typo" because commit statement is under "try" in this test. Maybe it should be under "try" also in case of merge ?
I am open for discussion :)
=> Module for IBM/Lenovo RackSwitch series.

ansible/napalm_install_config
Added a parameter to bypass generating diffs because some platforms don't support this, i.e. the Arista version I'm using 4.14.7M.  So, setting `get_diffs` to `False` will always apply the config and not attempt to "compare" the configs.
=> bypass diff generation in Ansible module for install_config

napalm/ibm.py
I have added timeout parameter to bnclient library, so now it can be used in napalm module for IBM/Lenovo devices. It solves #77 bug :)
=> timeout implemented in IBM module

docs/support/index.rst
ios works as stated in https://projectme10.wordpress.com/2015/12/07/adding-cisco-ios-support-to-napalm-network-automation-and-programmability-abstraction-layer-with-multivendor-support/
=> Update ios in index.rst

.gitignore, MANIFEST.in, Manifest.in
This also fixes the issue with ./napalm/utils/junos_views.yml not being copied when executing 'python setup.py install'.
=> MANIFEST.in is named incorrectly

docs/support/index.rst, napalm/junos.py
In the case of long standing sessions we don't want an exclusive lock on the config. Make this optional.
=> Make config lock optional on junos driver

napalm/utils/junos_views.yml
```lldp-local-interface``` (specific to JunOS < 13) vs ```lldp-local-port-id``` (JunOS >= 13) tags in LLDP XML RPC reply
=> JunOS 12.x and under vs. JunOS 13.x LLDP XML RPC

napalm/ios.py
There was a bug in the get_interface_counters code that was causing the get_interface_counters unit test to fail.
I was passing re.MULTILINE into the maxsplit argument instead of into the flags argument as I intended (as I was using positional argument instead of named arguments).
=> Fix re.split positional argument bug in get_interface_counters

.travis.yml, napalm/ios.py, test/unit/TestIOSDriver.py, test/unit/ios/mock_data/show_arp.txt
This replaces PR #178.
Rebased the code. Added the get_arp_table function from @ande0581. Added support for mock.
=> Add Cisco ios get_arp_table support

napalm/ios.py
changed the output for the get_interfaces() method to return the full interface name instead of the abbreviated name to keeps this consistent.
=> change output from abbreviated interface names to full names for IOS

.travis.yml, MANIFEST.in, docs/support/index.rst, napalm/base.py, napalm/eos.py, napalm/iosxr.py, napalm/junos.py, napalm/nxos.py, napalm/pluribus.py, napalm/utils/junos_views.yml, napalm/utils/textfsm_templates/eos/snmp_config.tpl, napalm/utils/textfsm_templates/nxos/snmp_config.tpl, test/unit/eos/mock_data/show_running_config_section_snmp_server.txt, test/unit/iosxr/mock_data/_Get__Configuration__SNMP___SNMP___Configuration___Get_.rpc, test/unit/junos/mock_data/_configuration__snmp__community____snmp___configuration_.txt, test/unit/nxos/mock_data/show_running-config___section_snmp-server.txt
I take this chance to introduce TextFSM parser (the library is required anyway by pycsco).
I am pretty sure this will be useful for other future implementations (from our side, we plan to refactor ```get_bgp_config``` and implement ```get_bgp_neighbors_detail``` for EOS and NXOS).
=> Add get_snmp_information() to JunOS, IOS-XR, NXOS & EOS

docs/support/index.rst
Just realised that ```get_route_to``` is missing. I rearranged the lines in such order that makes more sense to me -- but not necessarily to everyone. @dbarrosop it is just an idea, just close the PR if does not look good to you, but please add ```get_route_to```. Thanks!
=> Added get_route_to in support doc & rearranged lines

napalm/base.py, napalm/eos.py
interface_description is not needed for get_lldp_neigbhors_detail and is not currently present in the unit test models.py (so it is not currently implemented by platforms).
=> Remove interface_description from get_lldp_neighbors_detail

docs/support/ios.rst
Changed '' to `` for better visual representation on github.
Removed trailing whitespaces.
Added more precise Archive description.
=> Configuration file requirements.

.gitignore, docs/tutorials/Vagrantfile, docs/tutorials/index.rst, docs/tutorials/quickstart.rst
Replacement for https://github.com/napalm-automation/napalm/pull/235
Copying relevant content from that PR here:
Comments from here on are from @dbarrosop.  With this PR merged into the quickstart branch, I and others can start to address these points:
Change the current tutorials to use the same vagrantfile you have. With that I mean: http://napalm.readthedocs.org/en/latest/tutorials/index.html and http://napalm.readthedocs.org/en/latest/cli.html
Reference all the tutorials in your document. I think it's interesting that after seeing how simple the cli is they can jump into some python code and see that's it's almost as simple and not that different from using just the CLIs they are used to... Just a quick introduction to python code and then a link to the longer tutorial in the same way …
=> Quickstart

setup.py
A similar change was put into napalm-base in this PR https://github.com/napalm-automation/napalm-base/pull/24.
I thought this should also be in the napalm repository (to clarify that we currently only support Python2.7).
=> Add classifier indicating only Python2.7 support

setup.py
clitools has moved to napalm_base module.
Proposed fix for part of https://github.com/napalm-automation/napalm/issues/249
I didn't bump the version, I assume that the maintainers do that.
=> Remove bad clitools entry point.

docs/support/index.rst
Adding a small note to clarify the minimum supported version for Cisco Nexus devices.
=> Add note to clarify NXOS minumum supported version

docs/tutorials/index.rst, docs/tutorials/lab.rst, docs/tutorials/sample_scripts/load_replace.py, docs/tutorials/samples.rst
An initial example for discussion with @dbarrosop and anyone else interested.
This sample code builds on the virtual lab, so people can try out a running script immediately.
We could merge this into the quickstart branch and iterate on it, or I can fix up minor things here beforehand.
Future todos:
- add other samples.  Slack chat w/ DB: "would be cool to organize scripts by major feature: `context manager`, `load_merge`, `load_replace`, `load_template` ... then showing the `compare`, `discard`, `rollback`, etc... you would actually use the functional tests defined here as general idea"
- figure out how the docs should be arranged
- _somehow_ add unit tests to ensure that these things continue to work in the future.  I've manually tried it out and it works fine, but that's really not good …
=> Add load_replace tutorial example.

README.md
From time to time there are folks encountering issues using NAPALM and they simply paste a traceback of the error(s) they encounter, without providing any other piece of information, making debugging almost impossible till we get back and ask pretty much the same questions each and every time.
I suspect we will see this pattern more and more often and we should provide some guidelines to speed up this process.
@dbarrosop, @jzohrab Can you please give a helping hand?
=> Some guidelines for submitting issues

docs/support/index.rst
Descriptions from:
http://docs.paramiko.org/en/2.0/api/client.html?highlight=allow_agent
=> Adds SSH keys discovery extra args to doc

docs/cli.rst
First positional argument is the host, second positional is the configuration file. Not the reverse.
=> docs: fix cl_napalm_configure example

docs/installation/index.rst, docs/installation/ios.rst, docs/installation/iosxr.rst, docs/installation/junos.rst, docs/installation/panos.rst, docs/installation/pluribus.rst, docs/installation/vyos.rst
The current installation docs don't provide enough details when it comes to platform dependencies (http://napalm.readthedocs.io/en/latest/installation.html#dependencies)
Also, they depend on the driver the user needs to install. So I thought to separate them by the driver so the user can go straight and see what they need to install for each driver.
=> Better install docs

docs/validate/index.rst
The examples in the documentation for writing validator files is incorrect since landing the following, as yaml dicts were being converted to lists:
https://github.com/napalm-automation/napalm-base/pull/203/commits/b59144b0c92f127230034185e5175c267d92affe
When writing validators now, you must explicitly add each section of the validator as a list entry.
=> Cleaning up documentation for validator files

docs/support/index.rst
Updates the documentation to reflect the new `transport` optional argument
References:
* napalm-automation/napalm-ios#159
* napalm-automation/napalm-ios#132
* napalm-automation/napalm-eos#167
* napalm-automation/napalm-nxos#94
=> Change docs for `transport` argument

README.md
Removing the download counter which has stopped working:
[![PyPI](https://img.shields.io/pypi/dm/napalm.svg)](https://pypi.python.org/pypi/napalm)
It can give the wrong impression of the project. And of course, so that everything looks nice for the hacktoberfest. :)
=> Remove download counter which no longer works

napalm/ios/ios.py, test/ios/mocked_data/test_get_facts/old-2950/expected_result.json, test/ios/mocked_data/test_get_facts/old-2950/show_hosts.txt, test/ios/mocked_data/test_get_facts/old-2950/show_ip_interface_brief.txt, test/ios/mocked_data/test_get_facts/old-2950/show_version.txt
resolves #425 
Add unit test for old C2950 software and update version regex to correctly match the older version strings.
I do not have a large pool of Ciscos to test against, but this looks like a bug, and I don't _think_ it'll cause a regression.
=> Fix ios.get_facts() version checking for old versions of IOS

napalm/junos/junos.py, napalm/junos/utils/junos_views.yml, test/junos/mocked_data/test_get_ipv6_neighbors_table/normal/expected_result.json, test/junos/mocked_data/test_get_ipv6_neighbors_table/normal/get-ipv6-nd-information.xml
Support for `get_ipv6_neighbors_table()` in Junos
Note the `age` field is expiration time (same for `get_arp_table`)
=> Junos ipv6 neighbors table

napalm/_SUPPORTED_DRIVERS.py, napalm/base/validate.py, test/base/validate/test_unit.py
The reason to add `base` to `_SUPPORTED_DRIVERS` is to be able to install napalm without installing dependencies. The changes in the validate methods are to better reflect which one is supposed to be "public" and which one not.
=> Adding base in _SUPPORTED_DRIVERS and renaming functions

napalm/junos/constants.py, napalm/junos/junos.py, test/junos/mocked_data/test_get_optics/infinite_with_space/expected_result.json, test/junos/mocked_data/test_get_optics/infinite_with_space/get-interface-optics-diagnostics-information.xml
This fixes #491 where get_optics fails on some versions of JUNOS such as 12.3 because of a space in Infinite light levels.
=> Fix get_optics fail on some JUNOS versions

napalm/ios/ios.py, test/ios/mocked_data/test_get_probes_config/normal/expected_result.json, test/ios/mocked_data/test_get_probes_config/normal/show_run___include_ip_sla__0_9_.txt
Starting implementation for get_probes_config on ios. Only parses icmp-echo probes initially, but other probe types can easily be added.
=> ios: get_probes_config: driver implementation and test for icmp-echo

napalm/nxos_ssh/nxos_ssh.py, test/nxos_ssh/mocked_data/test_get_interfaces/5548_7_0_8_N1_1/expected_result.json, test/nxos_ssh/mocked_data/test_get_interfaces/alternate1/expected_result.json, test/nxos_ssh/mocked_data/test_get_interfaces/normal/expected_result.json
Add MTU to get_interface for the NXOS-SSH driver.
=> NXOS add mtu get interfaces

napalm/base/base.py, napalm/base/helpers.py
Also change behavior of abbreviated_interface so that name lookup attempt occurs regardless of failure of canonical name lookup.
Some minor name changes.
=> Fix dictionary update behavior for canonical name / abbreviated name

napalm/eos/eos.py, test/eos/mocked_data/test_get_interfaces/issue68_iface_no_physical_addr/expected_result.json, test/eos/mocked_data/test_get_interfaces/normal/expected_result.json
Update return values for `EOSDriver.get_interfaces() to return MTU.
Logical (loopback) interfaces are 65535, not sure if we want to change that?
=> (eos) Add mtu to get_interfaces()

docs/build-ansible-module-docs.sh
Before the NAPALM tests were picked up when running from RTD.
The Ansible Docs didn't build correctly on ReadTheDocs as the wrong tests were loaded.
=> Add "-c /dev/null" arguments to py.test command

docs/build-ansible-module-docs.sh, docs/test.sh
Before the NAPALM tests were picked up when running from RTD.
=> [docs] Add "-c /dev/null" arguments to py.test command (#561)

napalm/junos/junos.py
In Junos the mtu can be reported as `Unlimited`, force mtu to be `int` and return `-1` if `Unlimited`
```
<interface-information>
<physical-interface>
<name>lo0</name>
<admin-status junos:format="Enabled">up</admin-status>
<oper-status>up</oper-status>
<local-index>6</local-index>
<snmp-index>6</snmp-index>
<if-type>Loopback</if-type>
<mtu>Unlimited</mtu>
```
```
"lo0": {
"description": "", 
"is_enabled": true, 
"is_up": true, 
"last_flapped": -1.0, 
"mac_address": "Unspecified", 
"mtu": -1, 
"speed": -1
}, 
```
=> Junos force mtu to integer in get_interfaces()

tox.ini
Allow positional argument passing to tox.  This allows one to call specific tests and environments:
```
tox -e py36 -- test/base/test_get_network_driver.py::TestGetNetworkDriver::test_get_network_driver_1_base
GLOB sdist-make: /mnt/d/PyCharm/napalm/setup.py
py36 inst-nodeps: /mnt/d/PyCharm/napalm/.tox/dist/napalm-2.2.0.zip
py36 installed: asn1crypto==0.23.0,attrs==17.3.0,bcrypt==3.1.4,certifi==2017.11.5,cffi==1.11.2,chardet==3.0.4,coverage==4.4.2,coveralls==1.2.0,cryptography==2.1.3,ddt==1.1.1,docopt==0.6.2,flake8-import-order==0.16,future==0.16.0,idna==2.6,Jinja2==2.10,jtextfsm==0.3.1,junos-eznc==2.1.7,lxml==4.1.1,MarkupSafe==1.0,mccabe==0.6.1,mock==2.0.0,napalm==2.2.0,ncclient==0.5.3,netaddr==0.7.19,netmiko==1.4.3,paramiko==2.4.0,pbr==3.1.1,pluggy==0.6.0,py==1.5.2,pyasn1==0.4.2,pycodesty …
```
=> Permit tox/pytest argument passing

docs/contributing/index.rst, docs/support/index.rst
Didn't build cleanly:
```
pickling environment... done
checking consistency... /Users/mirucha/napalm/docs/contributing/core.rst: WARNING: document isn't included in any toctree
/Users/mirucha/napalm/docs/contributing/drivers.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] yang
/Users/mirucha/napalm/docs/contributing/core.rst:6: WARNING: undefined label: supported-devices (if the link has no caption the label must precede a section header)
```
=> Quick fix for the recently added docs

napalm/junos/junos.py, napalm/junos/utils/junos_views.yml
Support for VRF in get_arp() following #512 in Junos
```
ckishimo@ex9208> show arp vpn VRF | display xml rpc    
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/16.1R5/junos">
<rpc>
<get-arp-table-information>
<vpn>VRF</vpn>
</get-arp-table-information>
</rpc>
<cli>
<banner>[edit]</banner>
</cli>
</rpc-reply>
```
```
ckishimo@ex9208> show arp vpn VRF                      
MAC Address       Address         Name                      Interface               Flags
2c:21:31:a5:14:84 192.168.60.2    192.168.60.2              ge-3/1/3.0              none
```
```
[
{
"age": 882.0, 
"interface": "ge-3/1/3.0", 
"ip": "192.168.60.2", 
"mac": "2C:21:31:A5:14:84"
}
]
```
=> Junos vrf support in get_arp()

napalm/ios/ios.py, test/ios/mocked_data/test_get_environment/3850_16.06/expected_result.json, test/ios/mocked_data/test_get_environment/3850_16.06/show_env_temperature_status.txt, test/ios/mocked_data/test_get_environment/3850_16.06/show_memory_statistics.txt, test/ios/mocked_data/test_get_environment/3850_16.06/show_proc_cpu.txt
This PR fix #582 by reading the temperature sensor name instead of searching for a sensor named System.
All the temperature informations are return, keyed by their name.
=> Fix temperature for 3850 in 16.06 #582

napalm/eos/eos.py, napalm/ios/ios.py, test/eos/mocked_data/test_get_environment/issue80_stacktrace_for_get_environment/expected_result.json, test/eos/mocked_data/test_get_environment/issue90_veos/expected_result.json, test/eos/mocked_data/test_get_environment/normal/expected_result.json, test/ios/mocked_data/test_get_environment/3850_16.06/expected_result.json, test/ios/mocked_data/test_get_environment/normal/expected_result.json, test/ios/mocked_data/test_get_environment/temp_cmd_fail/expected_result.json
Report total memory instead of free memory for ios and eos drivers
=> Fix get_environnements available memory

napalm/iosxr/iosxr.py, test/iosxr/mocked_data/test_get_interfaces/normal/expected_result.json
An interface should always be considered enabled, unless the `shutdown` stanza is used in the configuration. If that’s the case, the XML API will set the state as `IM_STATE_ADMINDOWN`, opposed to `IM_STATE_DOWN` when the port is enabled, but there is no physical connectivity.
=> Interface is always enabled, unless explicitly specified in config

napalm/nxos_ssh/nxos_ssh.py, test/nxos_ssh/mocked_data/test_get_arp_table/normal/show_ip_arp_vrf_default___exc_INCOMPLETE.txt, test/nxos_ssh/mocked_data/test_get_mac_address_table/normal/expected_result.json, test/nxos_ssh/mocked_data/test_get_mac_address_table/normal/show_mac_address_table.txt
I happened to hit both of these today and saw an old issue open on one (#441) and created a new issue for discussion on the other (#633).  Attached are simple fixes for each that I patched into my local instance...
=> Fixes for CAM and ARP parsing issues in nxos_ssh.py

napalm/base/exceptions.py
Hi! I just had first go at writing a network automation script using napalm; I wanted to wrap my execution block in a try/except block, catching napalm-specific exceptions so that it would not exit the script, but to exit on other exceptions. In order to do this, I would have had to catch almost every listed exception class defined in base/exceptions.py individually.
I wrote a simple patch here to create a new generic NapalmException class, which inherits from Exception, and then modified each other exception class to subclass NapalmException instead. This way, I can list NapalmException as the only exception I need to catch, and then interrogate further for specific exception types if needed.
I've run the docs/test.sh script and all is good; let me know if there's further testing I …
=> improved exceptions - added new base exception

napalm/junos/junos.py
The named argument "msg" is now being returned (in this case the default of None).
before:
```
Traceback (most recent call last):
File "./test.py", line 17, in <module>
device.open()
File "/home/cspeidel/git/napalm_venv/lib/python2.7/site-packages/napalm/junos/junos.py", line 109, in open
raise ConnectionException(cte.message)
napalm.base.exceptions.ConnectionException
```
after:
```
Traceback (most recent call last):
File "./test.py", line 17, in <module>
device.open()
File "/home/cspeidel/git/napalm_venv/lib/python2.7/site-packages/napalm/junos/junos.py", line 109, in open
raise ConnectionException(cte.msg)
napalm.base.exceptions.ConnectionException: None
```
=> fixes #640 junos ConnectionException

.gitignore, napalm/nxos/nxos.py, napalm/nxos_ssh/nxos_ssh.py, test/nxos/mocked_data/test_ping/normal/expected_result.json, test/nxos/mocked_data/test_ping/normal/ping_8.8.8.8_timeout_2_packet-size_100_count_5.json, test/nxos/mocked_data/test_ping/ping_timed_out/expected_result.json, test/nxos/mocked_data/test_ping/ping_timed_out/ping_8.8.8.8_timeout_2_packet-size_100_count_5.json, test/nxos/mocked_data/test_ping/ping_unreachable/expected_result.json, test/nxos/mocked_data/test_ping/ping_unreachable/ping_8.8.8.8_timeout_2_packet-size_100_count_5.json, test/nxos_ssh/mocked_data/test_ping/normal/expected_result.json, test/nxos_ssh/mocked_data/test_ping/normal/ping_8_8_8_8_timeout_2_packet_size_100_count_5.txt
This is a restructuring of the PR that @mirceaulinic submitted.
=> NX-OS ping implementation using more shared common code

.travis.yml, Makefile, tox.ini
This PR adds an environment to test that the documentation in Sphinx is generated correctly.
In this first PR the `make html` test ignores warnings. The idea is to later change this and fail on warnings. There are currently a number of warnings generated when creating the documentation.
An example can be seen when looking at get_firewall_policies:
https://napalm.readthedocs.io/en/latest/base.html#napalm.base.base.NetworkDriver.get_firewall_policies
Compare the example of that function to get_interfaces:
https://napalm.readthedocs.io/en/latest/base.html#napalm.base.base.NetworkDriver.get_interfaces
If accepted I can look at those warnings and start to fix then and then set the test to fail on warnings.
=> Add test for sphinx documentation

Makefile, docs/support/ios.rst, docs/tutorials/lab.rst, napalm/base/base.py
There's currently a number of warnings generated by Sphinx as the documentation is built, this PR fixes the current issues and enable strict checking where the build will fail on a warning.
If you look in the current documentation you can see that a few of the getters have quite garbled data for the examples and such.
=> Fix garbled docstrings in RTD and enable strict checking for Sphinx

napalm/base/helpers.py, requirements.txt, test/base/test_helpers.py
Replace jtextfsm with textfsm.
jtextfsm has some Python3 compatibility issues in texttable.py. Also textfsm is now being supported again by Google.
=> Replace jtextfsm with textfsm

napalm/junos/junos.py
The same issue has been described before in `junos.py` and is an issue on multiple platforms. I tested the before and after on a EX4300-48P with success.
Concrete error before:
```
[lldp_neighbors_detail] cannot retrieve device data: RpcError(severity: error, bad_element: get-lldp-interface-neighbors-information, message: error: syntax error
```
=> The EX4300-48P has issues with LLDP information tags

.gitignore, napalm/ios/ios.py, napalm/ios/utils/textfsm_templates/show_lldp_neighbors.tpl, napalm/ios/utils/textfsm_templates/show_lldp_neighbors_detail.tpl, test/ios/mocked_data/test_get_lldp_neighbors/missing_hostname/expected_result.json, test/ios/mocked_data/test_get_lldp_neighbors/missing_hostname/show_lldp_neighbors.txt, test/ios/mocked_data/test_get_lldp_neighbors/missing_hostname/show_lldp_neighbors_detail.txt, test/ios/mocked_data/test_get_lldp_neighbors_detail/alternate2/expected_result.json, test/ios/mocked_data/test_get_lldp_neighbors_detail/alternate2/show_lldp_neighbors.txt, test/ios/mocked_data/test_get_lldp_neighbors_detail/alternate2/show_lldp_neighbors_detail.txt, test/ios/utils/textfsm_templates/show_lldp_neighbors.tpl, test/ios/utils/textfsm_templates/show_lldp_neighbors_detail.tpl
There is a bug where LLDP neighbors end up on the same interface when the remove device didn't have a system name and the LLDP output was missing `Local Intf` on older IOS versions.
This example returns the neighbor of interface Fa0/17 as being connected to Fa0/24.
```
Capability codes:
(R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
(W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID           Local Intf     Hold-time  Capability      Port ID
switch1             Fa0/24         120        B               Fa0/19
480f.cf28.8a1b      Fa0/17         3601                       480f.cf28.8a1b
Total entries displayed: 2
```
```
------------------------------------------------
Chassis id: a40c.c3c1.3980
Port id: Fa0/19
Port Description: FastEthernet0/19
System …
```
=> Fix issue with LLDP neighbors when remote device lacks system name on older IOS version

napalm/junos/junos.py
This PR adds support for `edit` and `top` keywords in `set` based configuration in Junos. The `edit` is used instead of `set` if one needs to add comments using the `annotate` statement as you need to be at the right hierarchy level 
For instance:
```
top edit system ntp
annotate peer 1.1.1.1 "Test ntp server"
system {
ntp {
/* Test ntp server */
peer 1.1.1.1;
peer 2.2.2.2;
}
}
```
One cannot add a comment with a single set command
=> junos: support edit/top keywords in set based configs

napalm/junos/junos.py
#802 
Destination in get_route_to other than junos (eg iosxr / eos) does not validate ip.
Also, there is a possibility that non-IP will be included in destionation in any OS. (VPNv 4)
junos has already parsed the value you get from the rpc response using `junos_views.yaml`.(https://github.com/napalm-automation/napalm/blob/develop/napalm/junos/utils/junos_views.yml) 
I think it was not necessary to verify the IP here.
=> Delete the ip validation of the destination of get_route_to in junos

napalm/junos/junos.py
Support added for:
Juniper srx300, ex2300-24p, ex2300-c-12p
Otherwise we get:
[lldp_neighbors_detail] cannot retrieve device data: RpcError(severity: error, bad_element: get-lldp-interface-neighbors-information, message: error: syntax error\nerror: syntax error)
=> junos lldp_neighbors_detail support for additonal models

napalm/eos/eos.py
If a bad destination is provided, raise an exception instead of returning a string.
=> Raise exception instead of returning string in `e.E.get_route_to()`

napalm/junos/junos.py
Include SW model QFX5100-48S-6Q to use rpc_call_without_information.
I encountered problems using lldp_neighbors_detail() for this switch model using Junos 17.3R3.9.
Modifying the RPC call fixes the issue like in other models.
=> QFX5100-48S-6Q to use rpc_call_without_information

napalm/base/validate.py, napalm/junos/utils/junos_views.py, test/junos/conftest.py
The default version of yaml.load allows you to load arbitrary python code (which we don't need/don't want).
Converting over to the safe_load which doesn't allow this.
=> Convert over to safe form of YAML load

docs/support/index.rst, napalm/nxos/nxos.py, requirements.txt
Update current version of pynxos >= 0.0.4: #784
Verify argument is exposed via ``verify`` key in ``optional_args``. It defaults to ``False`` for compatibility and can be set to ``True`` or any value allowed by requests library.
I kept the InsecureRequestWarning warnings from urllib3on purpose. These warnings can be easily blacked out.
I don't knwo how this code can be tested as the mocked driver use for the test bypass the open method.
I have just tested it against a live device.
=> Update pynxos to 0.0.4 and add verify optional_args to nxos

napalm/base/validate.py, test/base/validate/test_validate.py
Fixes #827
The validation operations in ```napalm/base/validate.py``` were modifying the source dictionnary passed as argument of ```compliance_report```.
This PR copy the original dictionnary to keep it untouched.
I have not seen any interest in creating another dataset for the tests. I used an existing one.
=> Prevent validation_source modification in validation process

docs/support/eos.rst
On vEOS 4.14.6M we get the following error with ``load candidate`` methods:
```pyeapi.eapilib.CommandError: Error [1003]: CLI command 2 of 2 'show configuration sessions' failed: unconverted command```
=> update docs with load conf methods not supported for vEOS < 4.15

napalm/junos/junos.py
That's strange but it would seem that with the current code, because of that one line, all pipes are ignored for junos `cli` function. 
I don't have access to any juniper device so I cannot test. If I'm right, it probably means that there should be unit tests with pipes for that `cli` function.
=> junos cli function: all pipes ignored ?

napalm/base/base.py
=> Fix timeout not being used when opening netmiko connection to IOS device

requirements.txt
This is due to CVE-2018-7750 and CVE-2018-1000805, and the underlying libraries may not have this requirement.
See https://nvd.nist.gov/vuln/detail/CVE-2018-7750 and https://nvd.nist.gov/vuln/detail/CVE-2018-1000805 for further details.
=> Enforce Paramiko >= 2.4.2

docs/tutorials/mock_driver.rst, napalm/base/mock.py
I stumbled upon this error during my tests:
`TypeError: 'NoneType' object is not subscriptable`
This is due to the fact that I was initializing the `MockDriver` without specifying a `path` to mock data in the `optional_args`. Or at this point in my tests I don't need the mock data so I'd like to be able to instantiate the driver with a default value.
=> Fix TypeError in mock driver initialization

setup.cfg, tox.ini
I struggled some time already to get the debugger on PyCharm working when running the test suite. I found out thatb ecause of the `--cov` option in `setup.cfg` this doesn't work.
ref: https://stackoverflow.com/a/40906766/10756636
This PR is to prevent other contributors that also use PyCharm from going through the same google-quest.
To prevent having command line options on 2 places, I extracted all command line options from `setup.cfg` and added them to `tox.ini`
=> Enable debugging tests in pycharm

napalm/junos/junos.py, test/junos/mocked_data/test_get_lldp_neighbors_detail/missing_port_ids/expected_result.json, test/junos/mocked_data/test_get_lldp_neighbors_detail/missing_port_ids/facts.yml, test/junos/mocked_data/test_get_lldp_neighbors_detail/missing_port_ids/get-lldp-interface-neighbors-information.xml, test/junos/mocked_data/test_get_lldp_neighbors_detail/missing_port_ids/get-lldp-neighbors-information.xml
Handle missing remote port in junos LLDP neighbors data.
In case there's no remote port, it'll return `None` instead of an empty string `""`
=> Handle missing remote port in junos LLDP neighbors data

napalm/eos/eos.py
Process optional_args in a way that supports arbitrary underlying
arguments in the pyeapi connection class used.
=> Refactor processing of EOS optional_args (#901)

napalm/eos/constants.py, test/eos/mocked_data/test_get_lldp_neighbors_detail/issue903/expected_result.json, test/eos/mocked_data/test_get_lldp_neighbors_detail/issue903/show_lldp_neighbors__detail.json
If anyone has any additional device output that highlights the JSON keywords for the other station types, it would be appreciated.
=> Update EOS LLDP type constant map.  Fixes #903

napalm/nxos_ssh/nxos_ssh.py, test/nxos_ssh/mocked_data/test_get_mac_address_table/alternate/expected_result.json, test/nxos_ssh/mocked_data/test_get_mac_address_table/multiple_interfaces/expected_result.json
On NXOS SSH, the `get_interfaces()` method returns interfaces like `Ethernet1/2/3` while `get_mac_address_table()` returns them like `Eth1/2/3`.
For being able to relate the mac table to the interfaces the two should be the same.
=> NXOS - Have get_mac_address_table return the same interface names as get_interfaces

napalm/base/base.py, napalm/eos/eos.py
Correct docstring regarding `last_flapped` key in return dictionary, and update EOS driver to return correct sentinel value of `-1.0` if data is not present.
=> Resolve issues in `get_interfaces()`

napalm/nxos_ssh/nxos_ssh.py, test/nxos_ssh/mocked_data/test_get_interfaces_ip/link_local_dumb_format/expected_result.json, test/nxos_ssh/mocked_data/test_get_interfaces_ip/link_local_dumb_format/show_ip_interface_vrf_all.txt, test/nxos_ssh/mocked_data/test_get_interfaces_ip/link_local_dumb_format/show_ipv6_interface_vrf_all.txt
Turns out that besides the following format:
``IPv6 link-local address: fe80::2ec2:60ff:fe4f:feb2 (default) [VALID]``,
Cisco Nexus also presents the IPv6 addresses under the following format:
``IPv6 address: fe80::2ec2:60ff:fe4f:feb2 [VALID]``.
=> Nexus SSH: Support another magic IP address line format

napalm/base/clitools/cl_napalm.py
Tiny fix for [napalm command line tools fails with 'Namespace' object has no attribute 'which'](https://github.com/napalm-automation/napalm/issues/936).
=> namespace fix for napalm cli

.github/ISSUE_TEMPLATE
When we used to maintain separare NAPALM drivers, we had an issue template
looking like this:
https://github.com/napalm-automation/napalm-junos/commit/110fec4bc9c50da43701b5019ecd859cc3c35f54#diff-faa36bc26a21ed93c8de974753b71507.
I was looking today through the issues we currently have open, and
I found some of them a bit chaotic, and hard to understand the context
/ environment the user runs. Additionally, some, e.g., #960, is really
hard to follow, and I've included a note to invite the user to check the
HitGub markdown manual.
=> Add GitHub issue template, as we used to have before

napalm/nxos/nxos.py, test/nxos/mocked_data/test_get_interfaces_ip/ipv6_n9k/expected_result.json, test/nxos/mocked_data/test_get_interfaces_ip/ipv6_n9k/show_ip_interface.json, test/nxos/mocked_data/test_get_interfaces_ip/ipv6_n9k/show_ipv6_interface.json
on at least nxos.9.2.3 the output has changed for ipv6 addresses. "addr" is no longer a top level key for each interface though "prefix" is. If multiple ipv6 addresses on an interface there is only one represented in "prefix" however.
=> support n9k ipv6 ints for interfaces_ip getter

napalm/junos/junos.py, napalm/junos/utils/junos_views.yml, test/junos/mocked_data/test_get_interfaces/normal/expected_result.json
Fixes https://github.com/napalm-automation/napalm/issues/942
=> support getting auto-negotiated speed on junos

napalm/base/base.py
Always try to close netmiko connections.
Closes #991
=> Better handling of connection closing upon exceptions in __enter__

napalm/nxos/nxos.py, test/nxos/mocked_data/test_get_interfaces_ip/ipv6_n9k/expected_result.json, test/nxos/mocked_data/test_get_interfaces_ip/ipv6_n9k/show_ipv6_interface.json
previous fix for n9k ipv6 interfaces only handled interfaces w/ multiple v6 addresses -- thinking that link local would show up. link local shows up in its own field so this broke interfaces w/ only one address -- fixed here.
=> address single and multiple v6 address on n9k

docs/installation/index.rst, docs/installation/ios.rst, docs/installation/iosxr.rst, docs/installation/junos.rst
Replace pip-based installation instructions for FreeBSD with instructions that use the native package management utility, pkg.
Close #934
=> Modernize docs for FreeBSD installation

docs/validate/index.rst
It currently 404s.
Note: This is a redo of #1001, to the correct branch.
=> Update link location in the docs

docs/contributing/index.rst
The documentation contribution section was sparse, so I tried to spruce it up a bit.
=> Clean up the documentation contribution section

napalm/junos/junos.py
I've encountered today an error, looking like:
```
'UnlockError' object has no attribute 'messsage'!
```
It look like we still have some small Python2 remains, as
<exception>.message is no longer valid syntax in Python3 (surprised that
the linter didn't catch that).
=> <exception>.message is no longer a thing in Python3

napalm/junos/junos.py
Adding an optional argument to the junos driver to select the DB config, as discussed in PR #1031 
Default to `committed`
=> junos add optional arg for DB config selection

napalm/nxos/nxos.py, test/nxos/mocked_data/test_get_environment/normal/expected_result.json, test/nxos/mocked_data/test_get_environment/normal/show_environment.json, test/nxos/mocked_data/test_get_environment/normal/show_processes_cpu.json, test/nxos/mocked_data/test_get_environment/normal/show_processes_memory_shared.json, test/nxos/mocked_data/test_get_environment/pre_7.0/expected_result.json, test/nxos/mocked_data/test_get_environment/pre_7.0/show_environment.json, test/nxos/mocked_data/test_get_environment/pre_7.0/show_processes_cpu.json, test/nxos/mocked_data/test_get_environment/pre_7.0/show_processes_memory_shared.json
This was tested on NXOS devices running 6.0(2)A8(11) and 7.0(3)I7(6), there were some API response changes between the two versions that are handled in the code.
=> Add get_environment support for NXOS driver

napalm/eos/eos.py
Cherry-picked and adapted @cuong-nguyenduy's commit from https://github.com/napalm-automation/napalm/pull/794.
=> When asPathType is Internal (IBGP), as_path is empty and the remote-as is the local_as

requirements.txt, test/junos/conftest.py
Since junos-eznc 2.3.0 the SAX parser is used as default. This is
enabled with "use_filter=True" at several locations. Thus disable it to
use the DOM parser that was used prior to pass the unittests.
This should fix #1060.
=> Fix unittests with junos-eznc 2.3.0

napalm/ios/ios.py
traceroute output with AS number parsed wrongly.
This small fix cleans up this:
Example hop parsed wrongly:
`  1 1.1.1.1 [AS 65200] 40 msec 40 msec 40 msec`
string after clean:
`1 1.1.1.1 40 msec 40 msec 40 msec`
=> FIX: traceroute output parsing in ios

requirements.txt
#1109 hard-pinned netmiko to 3.0.0 https://github.com/napalm-automation/napalm/blob/286667c3a80331301dd919e37edbb92ef41893c2/requirements.txt#L10 which is quite restrictive: when netmiko will get updated, napalm users will not be able to use it until `requirements.txt` is updated again and new release is published.  
This PR changes `netmiko==3.0.0` to `netmiko>=3.0.0`
=> Less strict netmiko constraints

napalm/nxos/nxos.py, test/nxos/mocked_data/test_get_environment/nxos_3k/expected_result.json, test/nxos/mocked_data/test_get_environment/nxos_3k/show_environment.json, test/nxos/mocked_data/test_get_environment/nxos_3k/show_processes_cpu.json, test/nxos/mocked_data/test_get_environment/nxos_3k/show_processes_memory_shared.json
Some Nexus devices postfix the names of the keys with the device's series information, ie `_n3k` in the case for Nexus 3k devices in the `show environment` output. This causes a `KeyError` exception to be thrown when trying to retrieve environmental data from the device using the `get_environment()` method. 
The currently method assumes that the key in the resulting JSON structure is `TABLE_psinfo` and subsequently `ROW_psinfo` which is not true for all Nexus devices. 
This fix uses the strategy deployed [here](https://github.com/ironick09/napalm/blob/902439e6b353a986f7843ccd6c047950bedcdfa3/napalm/nxos/nxos.py#L1385-L1389) to find the keys that start with `TABLE_psinfo` and `ROW_psinfo` and use those to index the JSON structure to find the environmental information. 
Additionally, newer …
=> Fix exception when trying to get environmental data from certain Nexus devices

.gitignore
For the VSCode IDE its useful to have local IDE setting in gitignore - `.vscode`
and for the users who leverage dev environment in containers - `.devcontainer`
=> adding .vscode and .devcontainer

napalm/nxos/nxos.py
`rr_sys_ver` reports the system version from before a reboot, not the current version. As the NXAPI seems to lack a straightforward `sys_ver_str` (This is why we’re in this mess in the first place), we’ll need to use the `kickstart_ver_str` instead.
This is also shown to be an issue in the official documentation: https://developer.cisco.com/docs/nx-api-cli-reference-for-the-cisco-nexus-9000-series-platform/#!version-commands/show-version
This fixes #1171
=> Use Kickstart version to determine NXOS version

napalm/pyIOSXR/iosxr.py, requirements.txt
Disabled Netmiko cmd_verify globally in pyIOSXR and now require at least netmiko 3.1.0.
Netmiko now defaults to cmd_verify=True in send_command.  This verifies that the sent text is echoed from the remote.  Devices in XML mode do not echo; therefore it timed out waiting.
Users can still enable global_cmd_verify by passing the option to the constructor or open method.
=> Fixed pyIOSXR XML mode timeout due to Netmiko cmd_verify

napalm/junos/junos.py, napalm/junos/utils/junos_views.yml, test/junos/conftest.py, test/junos/mocked_data/test_get_environment/issue1183_srx_multi_node/expected_result.json, test/junos/mocked_data/test_get_environment/issue1183_srx_multi_node/facts.yml, test/junos/mocked_data/test_get_environment/issue1183_srx_multi_node/get-environment-information.xml, test/junos/mocked_data/test_get_environment/issue1183_srx_multi_node/get-power-usage-information-detail.xml, test/junos/mocked_data/test_get_environment/issue1183_srx_multi_node/get-route-engine-information.xml, test/junos/mocked_data/test_get_environment/issue1183_srx_multi_node/get-temperature-threshold-information.xml
The usual replies look like:
```
mircea@switch> show chassis environment | display xml
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos">
<environment-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-chassis">
...
</environment-information>
</rpc-reply>
```
On SRX multi-node devices, the reply is encapsulated under the
``<multi-routing-engine-results><multi-routing-engine-item>`` tags,
e.g.,
```
mircea@srx> show chassis environment | display xml
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos">
<multi-routing-engine-results>
<multi-routing-engine-item>
<re-name>node0</re-name>
<environment-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-chassis">
...
</environment-information>
</multi-routing-engine-item> …
```
=> SRX cluster devices stack RPC replies under multi-routing-engine-results

napalm/base/helpers.py
Hi maintainers,
I propose to enhance the `find_txt` function so it won't log an error when it tries to get the text out of the element that has no text element present.
Consider the following example:
```python
import lxml
from napalm.base.helpers import find_txt
s = """
<port>
<port-id>1/1/c5/1</port-id>
<oper-state>up</oper-state>
<system-enabled-capabilities></system-enabled-capabilities>
</port>
"""
e = lxml.etree.fromstring(s)
print(
"element with text value:", find_txt(e, "oper-state", "default_value",),
)
print(
"element with no text value:",
find_txt(e, "system-enabled-capabilities", "default_value",),
)
```
In the XML snippet above, the current `find_txt` behaviour will log an error if one tries to get the text out of the element with not text value (second `print` func):
```bash …
```
=> lxml text retrieval (find_txt) shouldn't fail if no text element available

napalm/iosxr_netconf/constants.py, napalm/iosxr_netconf/iosxr_netconf.py
Define new optional argument (config_encoding) to specify the expected encoding in load_merge_config and load_replace_config. The get_config and compare_config methods now accept an encoding argument that can be set to "xml" or "cli". All encoding arguments default to "cli".
=> Add CLI support to configuration methods 

napalm/iosxr_netconf/constants.py, napalm/iosxr_netconf/iosxr_netconf.py, tox.ini
Exchange of configuration in XML format is limited to models in the `XR-only` module set.  The namespaces associated with the module set are gathered in the `open` method.  The `load_merge_candidate` and `load_replace_candidate` methods raise an exception (`MergeConfigException` and `ReplaceConfigException`,respectively) if unexpected data is detected.  The `get_config` and `compare_config` methods filter out any configuration associated with models not in the module set.  The models in the module set are determined using the YANG library model. If a device  doesn't support the YANG library model, explicit filtering is performed.
=> Add config filter for XR-only module set

napalm/eos/pyeapi_syntax_wrapper.py
eapi has some code internal to pyeapi whereby they call `self.run_commands` using positional arguments.
This can cause issues if you try to access the underlying pyeapi method directly from NAPALM (which I was doing in a certain context).
Here is an example call inside pyeapi that was breaking:
My code:
```python
napalm = task.host.get_connection("napalm", task.nornir.config)
eapi_conn = napalm.device
show_version = eapi_conn.enable("show version")
pprint(show_version)
```
Pyeapi internal code that would get called via the `enable()` method and was breaking because of the positional arguments:
https://github.com/arista-eosplus/pyeapi/blob/develop/pyeapi/client.py#L712
=> Allow positional arguments for run_commands in eapi Node override

napalm/eos/eos.py, napalm/ios/ios.py, test/eos/mocked_data/test_get_vlans/normal/expected_result.json, test/eos/mocked_data/test_get_vlans/normal/show_vlan.json
This would add the get_vlans() getter to the EOS network driver, which is currently not supported for the platform
=> Add get_vlans getter to EOS network driver

napalm/base/constants.py
`junos` was incorrectly mapped to `juniper_eos` instead of
`juniper_junos`. It shouldn't matter much as, AFAIK, `junos` is not
using Netmiko.
=> Fix mapping for Juniper devices with Netmiko

napalm/iosxr/iosxr.py
Due to a copy-paste probably, the code is currently looking under the
``instance_active_list``, which as the name suggests is a list of XML
trees, therefore any xpath query fails, with the following message.
Thanks to the newly added logging on the ``find_txt`` helper, the
following appeared in the logs:
```
'list' object has no attribute 'xpath'
'list' object has no attribute 'xpath'
'list' object has no attribute 'xpath'
'list' object has no attribute 'xpath'
'list' object has no attribute 'xpath'
'list' object has no attribute 'xpath'
```
This corrects this, by referencing the actual XML tree for the VRF
instead of the list of VRFs.
=> Look up the KeepAliveTime and HoldTime keys in the VRF tree

napalm/nxos_ssh/nxos_ssh.py
Removes unneeded print statement from interfaces_counters in nxos_ssh.py.
=> Remove Print Statement from nxos_ssh.py

napalm/nxos/nxos.py
I ran into a TypeError here: TypeError: unsupported operand type(s) for +=: 'int' and 'str'
Casting the uptime values (days, hours, mins, seconds) to int before processing fixes this issue.
=> Cast uptime values to int before processing

.travis.yml
The coverage badge seems to have been in a failed state for some time and the badge displays 0% code coverage.
This PR bumps the version of coveralls that Travis is using to one that is compatible with the current version of pytest-cov.
From the Travis log:
```
0.21s$ coveralls
Submitting coverage to coveralls.io...
Traceback (most recent call last):
File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/data.py", line 293, in read_file
self.read_fileobj(f)
File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/data.py", line 271, in read_fileobj
data = self._read_raw_data(file_obj)
File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/data.py", line 311, in _read_raw_data
go_away = file_obj.read(len(cls._GO_AWAY)) …
```
=> Bump version of coveralls to fix code coverage report

napalm/junos/junos.py
For example, for the following policy:
```
luca@bsr1.atl2> show configuration policy-options policy-statement INTERNAL-ATL2-RR-OUT
term LOCAL-BE {
from {
protocol static;
community PACKET-BE;
}
then {
local-preference 500;
next-hop self;
accept;
}
}
term LOCAL-PUBLIC {
from {
protocol static;
prefix-list ANNOUNCE-ATL2-V4;
}
then {
local-preference 500;
next-hop self;
accept;
}
}
term LOCAL-CUSTOMERS {
from {
protocol bgp;
community PACKET-ATL2-CUSTOMER;
route-filter 0.0.0.0/0 upto /24;
}
then {
next-hop self;
accept;
}
}
term GLOBAL-IP {
from {
protocol bgp;
community PACKET-ATL2-GLOBAL-IP;
}
then {
next-hop self;
accept;
}
}
term EVPN-REJECT-DEFAULT {
from {
protocol evpn;
route-filter 0.0.0.0/0 exact;
}
then reject;
}
term EVPN-PACKET-INTERNAL {
from {
family evpn;
community …
```
=> Multiple next-hop self config stanzas generate a list

napalm/base/base.py, napalm/base/helpers.py, napalm/eos/eos.py, napalm/junos/junos.py, napalm/pyIOSXR/iosxr.py
The behaviour for get-configuration RPC calls has been changed in
2af90cc75, in order to ensure we're gathering from the right database.
The way junos-eznc works is that if there aren't any specific options
passed in, it uses apply-groups by default. But when there are options
passed in, as we do starting with 2af90cc75, it doesn't default the
values of `inherit` and `groups`, and therefore when gathering the
config it won't expand the apply-groups, see
https://github.com/Juniper/py-junos-eznc/blob/ab0e8603eac56fa1d049695c7ef86eb64582ab8f/lib/jnpr/junos/factory/cfgtable.py#L517-L520.
Changing this now, by adding a few new optional arguments, which allow
the user to select the desired behaviour.
=> Use aply-groups inheritance on get-configuration RPC calls

napalm/eos/eos.py
Not sure how this was messed up earlier, but this bug was essentially disabling commit confirm behavior on EOS.
=> Fixing bug with commit confirm on EOS

napalm/base/mock.py
Fix discard_config counting up commit_config calls instead of discard_config.
=> Fix typo in mock.py

napalm/ios/ios.py, test/ios/mocked_data/test_get_interfaces/control-plane-interface/expected_result.json, test/ios/mocked_data/test_get_interfaces/control-plane-interface/show_interfaces.txt
See #1410 
I approached the fix by simply adding an additional regex pattern for the interface line. There are multiple approaches that are a matter of opinion, e.g. just modify existing pattern with an or to include the text but I chose this route. 
Also a matter of opinion is whether to handle this case and return the data or just skip it and exclude from the response as it seems to just be a bogus interface with no MAC, MTU, etc; however, I assume let the user handle that decision and just return the data as it is on the device which I think is inline with NAPALM principles.
Tests should also work to cover this case.
=> Handle control plane interface

napalm/iosxr/iosxr.py, test/iosxr/mocked_data/test_get_route_to/SR638170159/expected_result.json
This PR solves #1310. 
It is just a quick change in order to have the correct outgoing_interface when asking for a route to an IOSXR device.
It should work for all XR versions as long as the XML output does not change (which has not been the case since XR 4).
Hope this helps.
=> add outgoing_interface in get_route_to for isoxr

napalm/base/base.py, napalm/base/constants.py, napalm/eos/eos.py, napalm/ios/ios.py, napalm/junos/junos.py, napalm/nxos/nxos.py
Some vendors allow the definition of a `source interface` instead of the `source address` for the ping command with different keyword. For instance, [Junos](https://www.juniper.net/documentation/us/en/software/junos/icmp/topics/ref/command/ping.html).
Others don't use different keyword, so both arguments (`source` and `source_interface`) will end up using the same one.
=> Add source_interface argument to ping

napalm/junos/junos.py
when the command is `show xxx | display xml`, the result shows the raw XML format.
before this change: result like below
```
{"command | display xml": "<Element xxx xxxx>"}
```
the result of this change below
```
{"command | display xml": "
<rpc-reply>
<xxx>
</xxx>
</rpc-reply>"
}
```
=> change the function cli when result is xml object

requirements.txt
I am going to be releasing Netmiko 4.X some time in the next month or two.
Netmiko 4.X is very likely going to break NAPALM, so what I want to do is the following:
1. Pin NAPALM to use Netmiko version 3.X.X.
2. Release a version of NAPALM with this Netmiko pinning.
3. Release Netmiko 4.X.X. [Probably November/December]
4. Fix NAPALM such that it is compatible with Netmiko 4.X.X
This will ensure that NAPALM doesn't break when I release Netmiko 4.X.
Additionally, this will give us a lot more time to fix NAPALM to properly work with Netmiko 4.X.
=> Force Netmiko to be less than Netmiko version 4

napalm/junos/junos.py
Make a similar change to #1480 to allow more graceful recovery from expected configuration warnings (see [this comment](https://github.com/napalm-automation/napalm/pull/1480#issuecomment-905961019)).
The changes in [py-junos-eznc pull 1131](https://github.com/Juniper/py-junos-eznc/pull/1131) are included in junos_eznc-2.6.3 (I'm not sure which version first included the change).
=> if we are ignoring warnings on commit, also ignore them on discard

napalm/ios/ios.py
Sanitise input before building the regex with it
Current code fails when vlan_name begins with a regex special character such as "*"
=> Escape vlan_name before building regex string

napalm/iosxr_netconf/iosxr_netconf.py
Added support for optional args to isoxr_netconf.py driver to solve Issue #1394 ( IOSXR_NETCONF: Certain SSH arguments not supported).  Optional arguments are used as supplied, as passing through the netmiko_args() function in  netmiko_helpers for some reason removed some supplied (particularly  'hostkey_verify': False, 'look_for_keys': False) arguments, and I'm not able to work out why
=> Add optional arguments support to IOSXR NETCONF driver

.github/workflows/commit.yaml, mypy.ini, napalm/base/__init__.py, napalm/base/base.py, napalm/base/helpers.py, napalm/base/mock.py, napalm/base/netmiko_helpers.py, napalm/base/test/base.py, napalm/base/test/getters.py, napalm/base/test/models.py, napalm/base/utils/jinja_filters.py, napalm/base/utils/string_parsers.py, napalm/base/validate.py, napalm/nxapi_plumbing/api_client.py, napalm/nxapi_plumbing/device.py, napalm/nxapi_plumbing/errors.py, napalm/nxapi_plumbing/utilities.py, napalm/nxos/nxos.py, requirements-dev.txt, test/base/test_helpers.py, test/nxapi_plumbing/conftest.py, test/nxos/test_getters.py, test/nxos_ssh/test_getters.py
Something weird happened with #1434 so I redid the PR - again. This should be mostly free of any non-sense commits and should reflect a proper and useful implementation of type hinting for the NXOS parts of NAPALM.
=> Type hinting

napalm/ios/ios.py, test/ios/mocked_data/test_get_interfaces_ip/normal/expected_result.json, test/ios/mocked_data/test_get_lldp_neighbors/missing_hostname/expected_result.json, test/ios/mocked_data/test_get_lldp_neighbors_detail/alternate/expected_result.json, test/ios/mocked_data/test_get_lldp_neighbors_detail/alternate2/expected_result.json, test/ios/mocked_data/test_get_lldp_neighbors_detail/alternate4/expected_result.json, test/ios/mocked_data/test_get_lldp_neighbors_detail/device_id_20chars/expected_result.json, test/ios/mocked_data/test_get_lldp_neighbors_detail/device_id_20chars_space/expected_result.json, test/ios/mocked_data/test_get_lldp_neighbors_detail/missing_capability/expected_result.json, test/ios/mocked_data/test_get_lldp_neighbors_detail/normal/expected_result.json, test/ios/mocked_data/test_get_lldp_neighbors_detail/older_ios/expected_result.json, test/ios/mocked_data/test_traceroute/normal/expected_result.json
Adds mac / ip checks for:
```
get_lldp_neighbors
get_lldp_neighbors_detail
get_interfaces_ip
get_ntp_peers
traceroute
ping
``` 
Covers https://github.com/napalm-automation/napalm/issues/451
=> Adds mac, ip checks for getters

mypy.ini, napalm/base/helpers.py, napalm/ios/ios.py, requirements.txt
Fixes #1550 
This replaces parsing with [Netutils](https://netutils.readthedocs.io/en/latest/) to handle parsing of configuration lines. 
Testing thus far has been in a separate Python script that will get added as well to the PR. There were no previous tests written for the previous parser, so I found a basic BGP config for the first part to get the section bgp. The second and third configurations are tests with data from Cisco's documentation.
```
python try_netutils_config_parse.py
>>> NAPALM CURRENT HELPER (SECTION PARSING)
['router bgp 65010', ' bgp log-neighbor-changes', ' network 192.168.1.0', ' neighbor 192.0.2.1 remote-as 65550']
['router bgp 65010', ' bgp log-neighbor-changes', ' network 192.168.1.0', ' neighbor 192.0.2.1 remote-as 65550']
<<<< NETUTILS HELPER
>>> NAPALM CURRENT …
```
=> Replace confparse w netutils

mypy.ini, napalm/base/helpers.py, requirements-dev.txt, requirements.txt, test/base/test_helpers.py, test/base/utils/ttp_templates/bad_template.txt, test/base/utils/ttp_templates/good_template.txt
This PR developed as part of NANOG84 Hackathon efforts.
This PR add new helper function `ttp_parse`.
Debugging and developing regular expressions can be tedious process, for some use cases it is possible to use TTP as a drop in to produce same results but with less efforts. Besides parsing, TTP also might bring other use cases like results data validation, formatting, testing or postprocessing.
Updated `test/base/test_helpers.py` file with `test_ttp_parse` test that does 5 sub-tests:
* check if raises TemplateRenderException when template does not exist
* check if raises TemplateRenderException for /utils/ttp_templates/bad_template.txt
* check if returns expected result as output for ./utils/ttp_templates/good_template.txt
* check if returns expected result as output for inline template
* …
=> Add ttp_parse helper function to codebase

napalm/junos/junos.py, napalm/junos/utils/junos_views.yml, test/junos/mocked_data/test_get_bgp_neighbors/normal/expected_result.json, test/junos/mocked_data/test_get_bgp_neighbors/normal/get-bgp-neighbor-informationfrontend.xml, test/junos/mocked_data/test_get_bgp_neighbors/normal/get-bgp-summary-informationfrontend.xml
To avoid an additional RPC request to check the actual configuration, we
can probably use the Shutdown flag under the BGP extended options:
```xml
<bgp-options>Preference LocalAddress AddressFamily PeerAS Multipath Refresh</bgp-options>
<bgp-options2>VpnApplyExport PeerSpecficLoopsAllowed</bgp-options2>
<bgp-options-extended>GracefulShutdownRcv Shutdown</bgp-options-extended>
```
This should be a more reliable way to check the admin status, instead of
incorrectly deducing the admin state from the operational state.
=> Fix #1549: Check peer admin status from the BGP options

docs/support/nxos.rst, napalm/nxos/nxos.py, requirements.txt
NXOS partial merges were not aware of command hierarchy when showing the differences to be applied via the `compare_config` method. We (myself and @mundruid) have changed the merge diffing to use the [netutils](https://netutils.readthedocs.io/en/latest/) package. Docstrings and documentation updated as well.
Tests would be a stretch goal for another day since this code path is not tested at the moment.
See an example below of old and new behavior:
```
Intended configuration:
candidate_cfg = """
interface loopback0
ip address 10.1.4.5/32
ip router ospf 100 area 0.0.0.1
"""
Base - full configuration on device with the relevant section below:
...
interface loopback0
ip address 10.1.4.4/32
ip router ospf 100 area 0.0.0.1
...
nxos1.load_merge_candidate(config=candidate_cfg)
Before: …
```
=> Fix #1554: Improve compare_config for NXOS partial merging

napalm/nxos/nxos.py, test/nxos/mocked_data/test_get_interfaces/vlan_interface/expected_result.json, test/nxos/mocked_data/test_get_interfaces/vlan_interface/show_interface.json
Currently, all SVI in some NXOS devices report "" for description, because it comes from the property on `svi_desc`.
Signed-off-by: DavidVentura <davidventura27@gmail.com>
=> Fix description on SVI in NXOS

requirements-dev.txt
```
NOTE: This plugin is obsolete as of pytest 7.0.0. Thanks to this PR from
Brian Okken, you can now modify the PYTHONPATH using the pythonpath
configuration option. See documentation here:
https://docs.pytest.org/en/7.0.x/reference/reference.html#confval-pythonpath
```
=> Remove deprecated pytest-pythonpath

napalm/pyIOSXR/iosxr.py
https://github.com/ktbyers/netmiko/commit/4782157c920bb7f17f61b6ea9897ff2aa3bd78d6#diff-d624fe8122a167b02cbacae5860d4ecafb637c8837c02d285c122844a94667bc changed the path of these exceptions.
=> Fix pyIOSXR netmiko exception import path

.github/workflows/commit.yaml, .github/workflows/pythonpublish.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> Set permissions for GitHub actions

napalm/eos/eos.py, test/eos/conftest.py, test/eos/test_heredoc.py
In conjunction with #1643, if an arbitrary transport class is stateful, we should be trying to maintain state (exiting config mode after entering, closing when closing, etc).
=> Eos stateful

napalm/junos/junos.py
Continues #1637.
Closes #1500.
=> [Junos] Support JSON as output formats for CLI show commands

napalm/ios/utils/textfsm_templates/show_lldp_neighbors_detail.tpl
On an NCS-5500 the key is `Local Interface` instead of `Local Intf` when issuing `show lldp neighbors detail`. Search for both options.
=> add alternative lldp local interface key

napalm/eos/eos.py, test/eos/mocked_data/test_get_environment/issue1671_top_mb/expected_result.json, test/eos/mocked_data/test_get_environment/issue1671_top_mb/show_environment_cooling.json, test/eos/mocked_data/test_get_environment/issue1671_top_mb/show_environment_power.json, test/eos/mocked_data/test_get_environment/issue1671_top_mb/show_environment_temperature.json, test/eos/mocked_data/test_get_environment/issue1671_top_mb/show_processes_top_once.text, test/eos/mocked_data/test_get_environment/issue1671_top_mb/show_version.json
Arista EOS 4.27+ (and possibly earlier versions, untested on
4.24-4.26) changes the output from `show processes top once`
command, rendering values decimal numbers of MB instead of integer
numbers of KB, and also reorders the fields.
This commit extends the `get_environment` function with additional
logic to handle the output from both older and newer OS versions.
The memory expressed in MB is converted into KB for backward
compatibility, but because the switch has done some rounding and
displays only a limited number of decimal places, the conversion
into KB will not be exact. There is nothing that Napalm can do
about this.
Fixes #1671
=> Handle modern memory output from Arista EOS 4.27+

requirements.txt
Seems like textfsm 1.1.3 released this morning fails with
```
Traceback (most recent call last):
File "<string>", line 36, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/tmp/pip-install-mcywh0ov/textfsm_c69a342d098d4b31b41098cfba259f33/setup.py", line 20, in <module>
import textfsm
File "/tmp/pip-install-mcywh0ov/textfsm_c69a342d098d4b31b41098cfba259f33/textfsm/__init__.py", line 11, in <module>
from textfsm.parser import *
File "/tmp/pip-install-mcywh0ov/textfsm_c69a342d098d4b31b41098cfba259f33/textfsm/parser.py", line 41, in <module>
import six
ModuleNotFoundError: No module named 'six'
```
See also https://github.com/google/textfsm/issues/105.
=> Pin to textfsm<=1.1.2

docs/support/ios.rst, napalm/eos/eos.py, napalm/ios/ios.py, napalm/junos/junos.py, napalm/pyIOSXR/iosxr.py, test/base/test_helpers.py, test/pyiosxr/test_iosxr.py
There are small typos in:
- docs/support/ios.rst
- napalm/eos/eos.py
- napalm/ios/ios.py
- napalm/junos/junos.py
- napalm/pyIOSXR/iosxr.py
- test/base/test_helpers.py
- test/pyiosxr/test_iosxr.py
Fixes:
- Should read `uncommitted` rather than `uncommited`.
- Should read `retrieve` rather than `retrive`.
- Should read `retrieve` rather than `retreive`.
- Should read `millions` rather than `milions`.
- Should read `locally` rather than `localy`.
- Should read `interface` rather than `interfacece`.
- Should read `incorrect` rather than `incorrecet`.
- Should read `elements` rather than `lements`.
- Should read `argument` rather than `arguement`.
- Should read `against` rather than `agains`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE …
=> docs: Fix a few typos

napalm/base/helpers.py, napalm/eos/eos.py, napalm/ios/ios.py, napalm/iosxr/iosxr.py, napalm/iosxr_netconf/iosxr_netconf.py, napalm/nxos/nxos.py, napalm/nxos_ssh/nxos_ssh.py, test/base/test_helpers.py, test/eos/mocked_data/test_get_bgp_neighbors/issue1759/expected_result.json, test/eos/mocked_data/test_get_bgp_neighbors/issue1759/show_ip_bgp_summary_vrf_all.json, test/eos/mocked_data/test_get_bgp_neighbors/issue1759/show_ipv6_bgp_neighbors_vrf_all___include_IPv_46___Unicast_6PE_____0_9_____grep__v___IPv_46__Unicast_______remote_AS___Local_AS_Desc_BGP_state__remote.text, test/eos/mocked_data/test_get_bgp_neighbors/issue1759/show_ipv6_bgp_summary_vrf_all.json
Use built-in `ipaddress` library instead of external `netaddr` library.  
Primary driver is additional features -- `ipaddress` supports IPv6 address scope, while `netaddr` does not.
Resolves #1759
=> refactor: replace netaddr with ipaddress

.readthedocs.yml
Linked to #1697 
* Use python 3.8 to match CI documentation build version
* Install dev dependencies to fix build issue (missing packages pytest-cov and pytest-json)
This will fix the issue for https://readthedocs.org/projects/napalm/builds/18366967/
```bash
Running Sphinx v1.8.6
ERROR: usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --cov=./ --json=report.json
inifile: /dev/null
rootdir: /home/docs/checkouts/readthedocs.org/user_builds/napalm/checkouts/develop
```
=> [Fix] Readthedoc build config

requirements.txt
Reverts napalm-automation/napalm#1687 as https://github.com/google/textfsm/issues/105 seems to be fixed.
=> Revert "Pin to textfsm<=1.1.2"

napalm/base/base.py, napalm/eos/eos.py, napalm/ios/ios.py, napalm/iosxr/iosxr.py, napalm/iosxr_netconf/iosxr_netconf.py, napalm/junos/junos.py, napalm/junos/utils/junos_views.yml, test/eos/mocked_data/test_get_bgp_config/issue1504_alt_peer_group_syntax/expected_result.json, test/eos/mocked_data/test_get_bgp_config/issue_1113_dot_asn/expected_result.json, test/eos/mocked_data/test_get_bgp_config/normal/expected_result.json, test/ios/mocked_data/test_get_bgp_config/mixed_with_without_groups/expected_result.json, test/ios/mocked_data/test_get_bgp_config/no_afi/expected_result.json, test/ios/mocked_data/test_get_bgp_config/normal/expected_result.json, test/ios/mocked_data/test_get_bgp_config/peers_without_groups/expected_result.json, test/iosxr/mocked_data/test_get_bgp_config/mixed_with_without_groups/expected_result.json, test/iosxr/mocked_data/test_get_bgp_config/normal/expected_result.json, test/iosxr/mocked_data/test_get_bgp_config/peers_without_groups/expected_result.json, test/iosxr_netconf/mocked_data/test_get_bgp_config/normal/expected_result.json, test/junos/mocked_data/test_get_bgp_config/nhs/_configuration__routing_options__autonomous_system____routing_options___configuration_.xml, test/junos/mocked_data/test_get_bgp_config/nhs/expected_result.json, test/junos/mocked_data/test_get_bgp_config/normal/_configuration__routing_options__autonomous_system____routing_options___configuration_.xml, test/junos/mocked_data/test_get_bgp_config/normal/expected_result.json
Closes #1878
This changeset also includes logic to set the `local_as` in the group and neighbor dictionaries in the return value to the actual local AS instead of using `0` as a value to indicate it was not overridden
=> Update get_bgp_config to clarify return values

napalm/junos/junos.py
Currently if there is no BGP configuration on a Junos device you will get an exception when calling `get_bgp_config`
=> Fixing parsing error when there is no BGP configured on Junos

.github/workflows/commit.yaml, .github/workflows/pythonpublish.yml
Currently the CI jobs are showing warnings as the version of node in use is deprecated:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
=> Update actions/checkout@v3 actions/setup-python@v4

docs/support/index.rst, napalm/eos/eos.py
This allows the `self.config_session` to be invalidated on certain failures (right now a `discard_config()` failure).
=> EOS add force_cfg_session_invalid argument

napalm/nxos/nxos.py
Napalm was catching file transfer errors for NXOS without providing adequate details to debug. This change will expose the caught error
=> Update nxos.py to expose file transfer errors

requirements.txt
Now that we support Python >= 3.7, we can remove the requirement on the future module, which appears to be unused.
=> Remove future requirement

napalm/junos/junos.py
The code keeps breaking on this line: https://github.com/napalm-automation/napalm/blob/develop/napalm/junos/junos.py#L1339 
when there is a key that is not included in the [_GROUP_FIELDS_DATATYPE_MAP_](https://github.com/napalm-automation/napalm/blob/develop/napalm/junos/junos.py#L1247)
In particular, for the group names "multihop" and "cluster" this is a problem because it will inevitably show up in the router configs, but the datatype will always be None, which will provoke this error:
ValueError: Can't convert with callable None - no default is defined for this type.
originating from [here](https://github.com/napalm-automation/napalm/blob/develop/napalm/base/helpers.py#L471)
In previous versions, this `convert` function was not doing the type checks, so if it was just returning None. …
=> Fix `Can't convert with callable None` - for junos routers

napalm/nxos/nxos.py, napalm/nxos_ssh/nxos_ssh.py
The below PR made the 'changed' attribute obsolete, so removing it.
https://github.com/napalm-automation/napalm/pull/2006
=> Remove 'changed' attribute from nxos driver

.readthedocs.yml
Fix: #2065
I've upgraded python version to 3.11 as the github CI for the doc use 3.11
=> fix: documentation build
